version: '2.4'

services:
 bot:
   build: https://github.com/Encryptize/mikrus-recykling-notifer.git
   restart: unless-stopped
   environment:
    - TZ=Europe/Warsaw
   volumes:
    - ./data:/app/data